[package]
name = "nelsie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taffy = "0.3.17"
serde = { version = "1", features = ["derive"] }
serde_with = "3.4.0"
serde_json = "1"
resvg = "0.36.0"
usvg = "0.36.0"
usvg-tree = "0.36.0"
roxmltree = "0.18"
svg2pdf = "0.9.0"
thiserror = "1"
clap = { version = "4", features = ["derive"] }
svgtypes = "0.12.0"
log = "0.4"
env_logger = "0.10"
pdf-writer = "0.9"
itertools = "0.12.0"
imagesize = "0.12.0"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }